name: Docker Image CI/CD

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username glupekej --password ${{ secrets.GEHEIM }} ghcr.io
          docker build . --tag ghcr.io/glupekej/kiki:latest
          docker push ghcr.io/glupekej/kiki:latest